### ISSUE TITLE
v0.7 release checklist

### ISSUE THREAD

**Issue by alee** [comses/catalog#64]
- [x] data + schema migration: make prod database current
- [x] run clean_data
- [x] create production docker deployment, with regular db backups etc
- [x] functional test plan
- [x] request DNS changeover
- [x] assign publications currently assigned to Marco to the new students using the manage.py command #65

**Comment by cpritcha** [comment]
Test Plan Discovered Bugs:
------------------------------------------


- [ ] In the curate tab only the all field is displayed. Current site also COMPLETE, INVALID and NEEDS_AUTHOR_REVIEW catagories
